# The rules are helm templated, so we must escape labels:
# {{ $labels.target }} => {{"{{ $labels.target }}"}}
- alert: MariaDBReplicaSqlThreadNotRunning
  expr: |
    (
      mysql_slave_status_slave_sql_running{target=~"{{ include "mariadb-cluster.fullname" . }}.*"}
      and on (target)
      (mysql_slave_status_master_server_id{target=~"{{ include "mariadb-cluster.fullname" . }}.*"} > 0)
    ) == 0
  for: 1m
  labels:
    severity: critical
  annotations:
    summary: MariaDB replica does not have a running SQL replication thread
    description: |
      MariaDB replica {{"`{{ $labels.target }}`"}} does not have a running SQL replication thread
- alert: MariaDBReplicaIOThreadNotRunning
  expr: |
    (
      mysql_slave_status_slave_io_running{target=~"{{ include "mariadb-cluster.fullname" . }}.*"}
      and on (target)
      (mysql_slave_status_master_server_id{target=~"{{ include "mariadb-cluster.fullname" . }}.*"} > 0)
    ) == 0
  for: 1m
  labels:
    severity: critical
  annotations:
    summary: MariaDB replica does not have a running IO replication thread
    description: |
      MariaDB replica {{"`{{ $labels.target }}`"}} does not have a running IO replication thread
- alert: MariaDBReplicationLag
  expr: |
    (
      (
        mysql_slave_status_seconds_behind_master{target=~"{{ include "mariadb-cluster.fullname" . }}.*"} - mysql_slave_status_sql_delay{target=~"{{ include "mariadb-cluster.fullname" . }}.*"}
      )
      and on (target)
      (
        mysql_slave_status_master_server_id{target=~"{{ include "mariadb-cluster.fullname" . }}.*"} > 0
      )
    ) > 30
  for: 1m
  labels:
    severity: warning
  annotations:
    summary: MariaDB replica is lagging behind the primary
    description: |
      MariaDB replica {{"`{{ $labels.target }}`"}} is lagging behind the primary
- alert: MariaDBReplicaNotConfigured
  expr: |
    count(mysql_slave_status_master_server_id{target=~"{{ include "mariadb-cluster.fullname" . }}.*"}) != {{ sub .Values.mariadb.replicas 1 }}
  for: 5m
  labels:
    severity: critical
  annotations:
    summary: MariaDB cluster has instance(s) not configured as replicas
    description: |
      MariaDB cluster `{{ include "mariadb-cluster.fullname" . }}` has instance(s) not configured as replicas
