{{- include "mariadb-cluster.validateDatabases" . -}}
{{- range .Values.databases }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ include "mariadb-cluster.fullname" $ }}-{{ .name }}
  labels:
    {{- include "mariadb-cluster.labels" $ | nindent 4 }}
spec:
  mariaDbRef:
    name: {{ include "mariadb-cluster.fullname" $ }}
    namespace: {{ $.Release.Namespace }}
  {{- toYaml (unset (deepCopy .) "mariaDbRef" ) | nindent 2 }}
{{- end }}
