{{- include "mariadb-cluster.validateDatabases" . -}}
{{- range .Values.databases }}
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: {{ include "mariadb-cluster.fullname" $ }}-{{ .name }}
  namespace: {{ .namespace | default (include "mariadb-cluster.namespace" $) }}
  labels:
    {{- include "mariadb-cluster.labels" $ | nindent 4 }}
spec:
  mariaDbRef:
    name: {{ include "mariadb-cluster.fullname" $ }}
    namespace: {{ include "mariadb-cluster.namespace" $ }}
  {{- include "mariadb-cluster.omitKeys" (dict "object" . "keys" (list "namespace" "mariaDbRef") "nindent" 2) }}
{{- end }}
