apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "mariadb-cluster.fullname" . }}
  namespace: {{ include "mariadb-cluster.namespace" . }}
  labels:
    {{- include "mariadb-cluster.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.mariadb | nindent 2 }}
