nameOverride: ""
fullnameOverride: ""

# -- MariaDB CR
# https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#mariadbspec
mariadb:
  # affinity: {}
  # args: []
  # bootstrapFrom: {}
  # command: []
  # connection: {}
  # database: ""
  # env: []
  # envFrom: []
  galera:
    enabled: true
  # image: ""
  # imagePullPolicy: ""
  # imagePullSecrets: []
  # inheritMetadata: {}
  # initContainers: []
  # livenessProbe: {}
  # maxScale: {}
  # maxScaleRef: {}
  metrics:
    enabled: true
  # myCnf: |
  #   [mariadb]
  #   innodb_buffer_pool_size=1024M
  #   ignore_db_dirs=lost+found
  #   max_allowed_packet=256M
  # myCnfConfigMapKeyRef: {}
  # nodeSelector: {}
  # passwordPlugin: {}
  # passwordSecretKeyRef: {}
  # podDisruptionBudget: {}
  # podMetadata: {}
  # podSecurityContext: {}
  # port: ""
  # primaryConnection: {}
  # primaryService: {}
  # priorityClassName: ""
  # readinessProbe: {}
  replicas: 3
  # replicasAllowEvenNumber: false
  # replication:
  #   enabled: true
  # resources: {}
  rootPasswordSecretKeyRef:
    name: mariadb-cluster-root-password
    key: ROOT_PASSWORD
  # secondaryConnection: {}
  # secondaryService: {}
  # securityContext: {}
  # service: {}
  # serviceAccountName: ""
  # servicePorts: []
  # sidecarContainers: []
  # startupProbe: {}
  storage:
    size: 1Gi
  # suspend: false
  # timeZone: ""
  # tls: {}
  # tolerations: []
  # topologySpreadConstraints: []
  # updateStrategy: {}
  # username: ""
  # volumeMounts: []
  # volumes: []

# -- The list of Database CRs. The `.mariaDbRef` keys will be ignored. The `.name` keys are required to generate distinct CR names.
# https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#databasespec
databases: []
  # - characterSet: utf8
  #   cleanupPolicy: Delete
  #   collate: utf8_general_ci
  #   name: foo
  #   requeueInterval: 1h
  #   retryInterval: 3m

# -- The list of User CRs. The `.mariaDbRef` keys will be ignored. The `.name` keys are required to generate distinct CR names.
# https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#userspec
users: []
  # - cleanupPolicy: Delete
  #   host: "%"
  #   maxUserConnections: 100
  #   name: foo
  #   passwordHashSecretKeyRef: {}
  #   passwordPlugin: {}
  #   passwordSecretKeyRef: {}
  #   requeueInterval: 1h
  #   require: {}
  #   retryInterval: 3m

# -- The list of Grant CRs. The `.mariaDbRef` keys will be ignored. The `.username` keys are used to generate distinct CR names.
# https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#grantspec
grants: []
  # - cleanupPolicy: Delete
  #   database: foo
  #   grantOption: false
  #   host: "%"
  #   privileges:
  #     - ALL PRIVILEGES
  #   requeueInterval: 1h
  #   retryInterval: 3m
  #   table: "*"
  #   username: foo

# -- The list of Backup CRs. The `.mariaDbRef` keys will be ignored. The CR names will have list index suffixes.
# https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/API_REFERENCE.md#backupspec
backups: []
  # - affinity: {}
  #   args: []
  #   backoffLimit: 2
  #   compression: gzip
  #   databases: []
  #   failedJobsHistoryLimit: 3
  #   ignoreGlobalPriv: true
  #   imagePullSecrets: []
  #   inheritMetadata: {}
  #   logLevel: info
  #   maxRetention: 336h
  #   nodeSelector: {}
  #   podMetadata: {}
  #   podSecurityContext: {}
  #   priorityClassName: ""
  #   resources: {}
  #   restartPolicy: OnFailure
  #   schedule:
  #     cron: "0 0 * * *"
  #   securityContext: {}
  #   serviceAccountName: ""
  #   stagingStorage: {}
  #   storage:
  #     s3:
  #       bucket: backups
  #       endpoint: minio.minio.svc.cluster.local:9000
  #       prefix: mariadb
  #       accessKeyIdSecretKeyRef:
  #         name: mariadb-cluster-aws-creds
  #         key: AWS_ACCESS_KEY_ID
  #       secretAccessKeySecretKeyRef:
  #         name: mariadb-cluster-aws-creds
  #         key: AWS_SECRET_ACCESS_KEY
  #   successfulJobsHistoryLimit: 3
  #   timeZone: ""
  #   tolerations: []
